export default{
    products:[{
        _id: '1',
        status: "new",
        name: "Product Title 10011",
        image: "./images/thumb_DM4A300.jpg",
        detailImage: "../images/thumb_DM4A300.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi nganh giay",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '2',
        status: "new",
        name: "Product Title 10011",
        image: "./images/On-line_Analyzer_UV.jpg",
        detailImage: "../images/On-line_Analyzer_UV.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi nganh giay",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '3',
        status: "new",
        name: "Product Title 10011",
        image: "./images/thumb_300_ap_500-m6_977.png",
        detailImage: "../images/thumb_300_ap_500-m6_977.png",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi nganh xay dung",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '4',
        status: "new",
        name: "Product Title 10011",
        image: "./images/thumb_HS_7VAAWTCA8__R1Z7BC3E2.jpg",
        detailImage: "../images/thumb_HS_7VAAWTCA8__R1Z7BC3E2.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi nganh thuc pham",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '5',
        status: "hot",
        name: "Product Title 10011",
        image: "./images/Thumb_N5900_PC.jpg",
        detailImage: "../images/Thumb_N5900_PC.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi nganh y",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '6',
        status: "hot",
        name: "Product Title 10011",
        image: "./images/thumb_ad4a.jpg",
        detailImage: "../images/thumb_ad4a.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi phong thi nghiem",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '6',
        status: "hot",
        name: "Product Title 10011",
        image: "./images/thumb_ad4a.jpg",
        detailImage: "../images/thumb_ad4a.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi phong thi nghiem",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    },
    {
        _id: '6',
        status: "hot",
        name: "Product Title 10011",
        image: "./images/thumb_ad4a.jpg",
        detailImage: "../images/thumb_ad4a.jpg",
        hangsx: "Lorem ipsum dolor sit amet.",
        model: "Lorem ipsum dolor sit amet.",
        loaihang: "thiet bi phong thi nghiem",
        mota:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta condimentum lectus, ut rutrum ante vehicula a. Pellentesque ligula nisl, euismod eu tortor mollis, consectetur semper lacus. Curabitur nec lobortis tortor, sit amet venenatis nisi. Etiam luctus facilisis lectus, consequat lobortis mauris mattis eget. Maecenas in magna dolor.",
    }
]}